import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "FindWork on WaterlooWorks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
            <Navbar />
            {children}
        </div>
      </body>
    </html>
  );
}
