import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "FindWork on WaterlooWorks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
        <div className="h-full w-full flex">
          <div className="h-full w-fit">
            <Navbar />
          </div>
          <div className="h-full w-full flex items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
